name: tmb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - statsmodels
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - openpyxl
  - pyarrow
  - requests
  - tqdm
  - pip
  - pip:
      - firthlogist
      - black
      - ruff
